### ISSUE TITLE
Metadata API: Entities with empty descriptions

### ISSUE THREAD

**Issue by CodingDive** [serlo/database-layer#382]
Property: https://dini-ag-kim.github.io/amb/draft/#description

- [x] serlo/database-layer#406
- [x] serlo/private-issues-sso-metadata-wallet#13
- [x] serlo/private-issues-sso-metadata-wallet#14
